### ISSUE TITLE
国外模组开发教程资源

### ISSUE THREAD

**Issue by 3TUSK** [mousesrc/MinecraftDeveloperGuide#1]
居然没有下面这两个：
* http://modwiki.temporal-reality.com/mw/index.php/Main_Page
* http://www.pahimar.com/tutorials/lets-mod/

**Comment by mousesrc** [comment]
下次更新添加

**Comment by mousesrc** [comment]
第二个教程的内容有点少

**Comment by mousesrc** [comment]
已更新
